version: '3'

services:
  api:
    build: .
    restart: unless-stopped
    command: npm run start
    container_name: api
    depends_on:
      - db
    ports:
      - "3001:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
#      DB_NAME: dictionary
      JWT_SECRET: secret
  db:
    image: postgres:15.1-alpine3.16
    restart: unless-stopped
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
#      POSTGRES_DB: dictionary
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: